services:
  validator:
    image: docker.io/lifeofpavs/solana-test-validator:latest
    command: [
        "solana-test-validator",
        "-r", # Reset
        #"-q", # disable quiet so that we know when the validator is ready when it starts producing blocks

        # Warp to epoch 1 so that we can test with fully active stake accounts
        #
        # Set a low slot per epoch so that init doesnt take too long,
        # but long enough for all tests to run in the same epoch.
        "--slots-per-epoch",
        "3600",
        "--warp-slot",
        "4000",

        # Load test fixtures accounts
        "--account-dir",
        "/test-fixtures",

        # Programs
        "--upgradeable-program",
        "unpXTU2Ndrc7WWNyEhQWe4udTzSibLPi25SXv2xbCHQ",
        "/test-fixtures/programs/unstake.so",
        "none",

        "--upgradeable-program",
        "SP12tWFxD9oJsVWNavTTBZvMbA6gkAmxtVgxdqvyvhY",
        "/test-fixtures/programs/single-validator-stake-pool.so",
        "none",

        "--upgradeable-program",
        "SPMBzsVUuoHA4Jm6KunbsotaahvVikZs1JyTW6iJvbn",
        "/test-fixtures/programs/multiple-validator-stake-pool.so",
        "none",

        "--upgradeable-program",
        "SPoo1Ku8WFXoNDMHPsrGSTSG1Y47rzgn41SLUNakuHy",
        "/test-fixtures/programs/stake-pool.so",
        "none",

        "--upgradeable-program",
        "MarBmsSgKXdrN1egZf5sqe1TMai9K1rChYNDJgjq7aD",
        "/test-fixtures/programs/marinade.so",
        "none",

        "--upgradeable-program",
        "CrX7kMhLC3cSsXJdT7JDgqrRVWGnUpX3gfEfxxU2NVLi",
        "/test-fixtures/programs/lido.so",
        "none",

        "--upgradeable-program",
        "stkitrT1Uoy18Dk1fTrgPw8W6MVzoCfYoAFT4MLsmhq",
        "/test-fixtures/programs/stakedex.so",
        "none",

        "--deactivate-feature",
        "9onWzzvCzNC2jfhxxeqRgs5q7nFAAKpCUvkj6T6GJK9i", # deactivate 1 SOL minimum delegation stake
      ]
    volumes:
      - ./test-fixtures:/test-fixtures
    healthcheck:
      test: ["CMD", "solana", "cluster-version", "-u", "http://localhost:8899"]
      interval: 5s
      timeout: 5s
      retries: 20
    ports:
      - "8899:8899" # http rpc
      - "8900:8900" # websocket rpc
