services:
  validator:
    image: docker.io/lifeofpavs/solana-test-validator:latest
    command: [
        "solana-test-validator",
        "-r", # Reset flag
        "--account-dir",
        "/test-fixtures",
        "--bpf-program",
        "unpXTU2Ndrc7WWNyEhQWe4udTzSibLPi25SXv2xbCHQ",
        "/test-fixtures/programs/unstake.so",
        "--bpf-program",
        "SP12tWFxD9oJsVWNavTTBZvMbA6gkAmxtVgxdqvyvhY",
        "/test-fixtures/programs/single-validator-stake-pool.so",
        "--bpf-program",
        "SPMBzsVUuoHA4Jm6KunbsotaahvVikZs1JyTW6iJvbn",
        "/test-fixtures/programs/multiple-validator-stake-pool.so",
        "--bpf-program",
        "SPoo1Ku8WFXoNDMHPsrGSTSG1Y47rzgn41SLUNakuHy",
        "/test-fixtures/programs/stake-pool.so",
        "--bpf-program",
        "stkitrT1Uoy18Dk1fTrgPw8W6MVzoCfYoAFT4MLsmhq",
        "/test-fixtures/programs/stakedex.so",
        "--bpf-program",
        "MarBmsSgKXdrN1egZf5sqe1TMai9K1rChYNDJgjq7aD",
        "/test-fixtures/programs/marinade.so",
        "--deactivate-feature",
        "9onWzzvCzNC2jfhxxeqRgs5q7nFAAKpCUvkj6T6GJK9i", # deactivate 1 SOL minimum delegation stake
        "-um",
      ]
    volumes:
      - ./test-fixtures:/test-fixtures
    ports:
      - "8899:8899" # http rpc
      - "8900:8900" # websocket rpc
